### ISSUE TITLE
Fatal error on blog post page

### ISSUE THREAD

**Issue by ardalann** [IhorVansach/Blog-Extension-for-Magento-2#1]
I got the error below right after installing the extension on a fresh Magento installation when visiting this URL: ```/index.php/blog/post/hello-world/```
```
Fatal error: Call to a member function getId() on null in 
app\code\Magefan\Blog\Block\Post\View\RelatedProducts.php on line 126
```

**Comment by IhorVansach** [comment]
Hello Ardalan,

Sorry for inconvenience.

I fixed it.
Could you please update your local file app\code\Magefan\Blog\Block\Post\View\RelatedProducts.php ?

Source: https://github.com/IhorVansach/Blog-Extension-for-Magento-2/blob/master/app/code/Magefan/Blog/Block/Post/View/RelatedProducts.php

Regards,
Ihor

**Comment by cmcandrew** [comment]
Hi Ihor,

I noticed this issue, applied the recent update and once you add a related product the admin section for Related Products refuses to load console error:
``POST http://magento2.dev/admin_ps8ydc/blog/post/relatedProducts/id/3/key/faac3711d3f5ac0c79a81c5f2f80441df78086d059d923ad8da2283c85c0976c/ 500 (Internal Server Error)``
``jquery.js:9666: xhr.send( ( options.hasContent && options.data ) || null );``

Frontend loses all styles, templates and displays:  
Posted: December 22, 2015
Blah blah blah.

Related Products

Any ideas?

**Comment by IhorVansach** [comment]
Hello Cmcandrew,

Thank you for report.
We have made changes. Please update Blog Extension for Magento 2

Regards,
Ihor
