### ISSUE TITLE
Wrong image url.

### ISSUE THREAD

**Issue by swnsma** [IhorVansach/Blog-Extension-for-Magento-2#10]
If I use 'pub' folder as directory root in website configs, it give a wrong image url.
Should be 
domain.local/media/magefan_blog/s/e/selection_010.png,
give 
domain.local/pub/media/magefan_blog/s/e/selection_010.png
As result, image not found.
I think, better use \Magento\Store\Model\Store object to find url in:
\Magefan\Blog\Model\Url::getMediaUrl

**Comment by IhorVansach** [comment]
Try update file
app/code/Magefan/Blog/Model/Url.php
to the last version from repo.

**Comment by swnsma** [comment]
Thanks.
Now work well.
