### ISSUE TITLE
Post Categories in menu 

### ISSUE THREAD

**Issue by vickkeane** [IhorVansach/Blog-Extension-for-Magento-2#11]
Hi 
How to get the post categories in top menu in this modules .
Thanks

**Comment by IhorVansach** [comment]
This is require custom development.

To get blog categories tree you can use this code

```
$categoryCollection = \Magento\Framework\App\ObjectManager::getInstance()
            ->create('Magefan\Blog\Model\ResourceModel\Category\Collection');

$categoeies = $categoryCollection
    ->addActiveFilter()
    ->addStoreFilter($this->_storeManager->getStore()->getId())
    ->setOrder('position')
    ->getTreeOrderedArray();

```
Similar to block
 \Magefan\Blog\Block\Sidebar::getGroupedChilds
and template view frontend/templates/sidebar/categories.phtml

If you wont we can do it for you. You can contact us http://magefan.com/contact/ to get a quote.
