### ISSUE TITLE
error during compile

### ISSUE THREAD

**Issue by gdub01** [IhorVansach/Blog-Extension-for-Magento-2#2]
Thanks for this module! It works great in development mode for me. 

However, when I go to deploy to production, when it compiles I get this: 

Magento\Framework\App\Action\Forward\Interceptor
Errors during compilation:
	Magefan\Blog\Block\Post\PostList\AbstractList
		Incorrect dependency in class Magefan\Blog\Block\Post\PostList\AbstractList in /var/www/html/magento/vendor/magefan/blog/Block/Post/PostList/AbstractList.php
\Magento\Store\Model\StoreManagerInterface already exists in context object
\Magento\Framework\View\Page\Config already exists in context object
	Magefan\Blog\Block\Post\View\RelatedProducts
		Incorrect dependency in class Magefan\Blog\Block\Post\View\RelatedProducts in /var/www/html/magento/vendor/magefan/blog/Block/Post/View/RelatedProducts.php
\Magento\Framework\Registry already exists in context object
	Magefan\Blog\Block\Post\AbstractPost
		Incorrect dependency in class Magefan\Blog\Block\Post\AbstractPost in /var/www/html/magento/vendor/magefan/blog/Block/Post/AbstractPost.php
\Magento\Store\Model\StoreManagerInterface already exists in context object
	Magefan\Blog\Block\Sidebar\Categories
		Incorrect dependency in class Magefan\Blog\Block\Sidebar\Categories in /var/www/html/magento/vendor/magefan/blog/Block/Sidebar/Categories.php
\Magento\Store\Model\StoreManagerInterface already exists in context object
Total Errors Count: 4
Compilation complete
Disabled maintenance mode
Enabled production mode.

Any ideas why that's happening? I've included your module with composer and it does work in development. Just compiling to production, or even running di:compile causes this error to appear.

**Comment by IhorVansach** [comment]
Gavin, thank you for report.

There was extra (unneeded) properties in some blocks declarations.
I pushed changes so please update our blog extension for magento 2 and let me know if everything is OK now.

Regards

**Comment by gdub01** [comment]
Thanks so much! It compiled perfectly.
