### ISSUE TITLE
Hardcoded Facebook and Disqus accounts in comments.phtml

### ISSUE THREAD

**Issue by devdesco-ceo** [IhorVansach/Blog-Extension-for-Magento-2#3]
Please refine your code to remove hardcoded Facebook and Disqus accounts in comments.phtml:

facebook app id - 416086851745150
disqus shortname - glyadyk

**Comment by IhorVansach** [comment]
Thank you. It is done. Please update you local code.

**Comment by devdesco-ceo** [comment]
Thanks
