### ISSUE TITLE
Empty URL key doesn't auto generate

### ISSUE THREAD

**Issue by pivulic** [IhorVansach/Blog-Extension-for-Magento-2#4]
## Problem
Saving a category/post where the URL-key is empty throws an exception: http://www.vaimo.com/snaps/pablo.ivulic/magefan-empty-url-key.png

## Expected result
If the URL-key field is empty, the module should auto generate a URL friendly key based on the category/post title, similar when saving a regular product or category in Magento.

**Comment by IhorVansach** [comment]
Pablo, this is not really a bug. "Auto generate URL" feature was not included in current release. It will be added in future 2-3 weeks.

**Comment by IhorVansach** [comment]
Pablo, please update your you local files. Don't forget to run php bin/magento setup:upgrade

**Comment by pivulic** [comment]
:+1:
