### ISSUE TITLE
Post does not appear in parent category

### ISSUE THREAD

**Issue by pivulic** [IhorVansach/Blog-Extension-for-Magento-2#5]
##Problem
If a post is enabled in a sub-category, it doesn't appear on the parent category. See: http://www.vaimo.com/snaps/pablo.ivulic/magefan-no-category-anchor-support.png

##Expected result
This post should appear in Electronics and in Electronics/Phones

**Comment by IhorVansach** [comment]
Hello Pablo, thank you for your report. The issue is fixed. Please update you local code.

**Comment by pivulic** [comment]
Thanks! 

Two other questions, 
1) Will you release a new version in https://github.com/IhorVansach/Blog-Extension-for-Magento-2/releases?

2) Could you package your module on a package server, i.e. https://packagist.org/ or similar, since one of the best way of installing modules in Magento 2 is by using composer? Similar to https://packagist.org/packages/narayanvarma/magento2-google-tagmanager where we can easy install the module using composer (the source code is still located in https://github.com/narayanvarma/magento2-google-tagmanager).

**Comment by IhorVansach** [comment]
Pablo
1. Yes, after we add blog tags and  "Auto generate URL" we will release new version. Estimate time 2-3 weeks
2.  We look at it. Thank you. Also we are waiting for opening Magento marketplace, so anyone can install extension right from admin panel without any technical knowledge.

Pablo, can this issue be closed?

**Comment by pivulic** [comment]
1) Sounds good :)

2) Ok. However, Marketplace is not an option for us, since we rely on our internal deployment workflow and that requires to use packages (which is why we have forked your module and created our own package as a temporary solution). 

Yes, this issue can be closed :)
