### ISSUE TITLE
posts are not added to the sitemap

### ISSUE THREAD

**Issue by Wojton** [IhorVansach/Blog-Extension-for-Magento-2#6]
in Magento\Sitemap\Model\Sitemap\SitemapPlagin.php 
$subject->addSitemapItems($sitemapItem); 
Method 'addSitemapItems' does not exist and posts are not added to the sitemap

**Comment by IhorVansach** [comment]
Hello Piotr, this issue is fixed. Please update you local code.

**Comment by Wojton** [comment]
Hi,
Map does not show up correctly.
Invalid path for posts. It is only the main domain.
Example:
<url><loc>http://domain.dev/</loc><changefreq>weekly</changefreq><priority>0.25</priority></url>
<url><loc>http://domain.dev/</loc><changefreq>weekly</changefreq><priority>0.25</priority></url>

**Comment by IhorVansach** [comment]
Piotr, we cannot replicate the issue on our end. Could you please send to us your ftp and admin panel credentials, so we can check and fix that.
Email: support@magefan.com
Contact form: http://magefan.com/#contact

If you are working on localhost, we can solve this problem using teamviewer.

**Comment by Wojton** [comment]
The  category should be added parameter $this->getStoreId()
Sitemap is generated correctly.

```
(...)
     $this->_sitemapItems[] = new \Magento\Framework\DataObject(
            [
                'changefreq' => 'weekly',
                'priority' => '0.25',
                'collection' =>  \Magento\Framework\App\ObjectManager::getInstance()->create(
                        'Magefan\Blog\Model\Category'
                      )->getCollection($this->getStoreId())
                    ->addStoreFilter($this->getStoreId())
                    ->addActiveFilter(),
            ]
        );
(...)
```

**Comment by IhorVansach** [comment]
Thank you Piotr. $this->getStoreId() has been added. Can this issue be closed?
