### ISSUE TITLE
Related products on installation with multi-websites

### ISSUE THREAD

**Issue by swnsma** [IhorVansach/Blog-Extension-for-Magento-2#9]
Hello, I have a problem.
I have Magento 2 installation and use 2 different websites. Some of the products are used in both websites. When I try to open list of products it gives me the error.
Problem that in \Magefan\Blog\Block\Adminhtml\Post\Edit\Tab\RelatedProducts::_prepareCollection it joins websites to product collection, so it gives collection without unique entity_ids (products records are duplicated) and can't works with it.

**Comment by IhorVansach** [comment]
Pls try fix from last commit. Update file  app/code/Magefan/Blog/Block/Adminhtml/Post/Edit/Tab/RelatedProducts.php

**Comment by swnsma** [comment]
Thanks.
